[project]
name = "proyecto-capstone-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "matplotlib>=3.10.3",
    "mplsoccer>=1.4.0",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "supervision>=0.25.1",
    "ultralytics>=8.3.144",
]
